- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: enable and disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create user
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download cart applications
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart.zip 
      dest: /tmp

  - name: extract cart applcations 
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: instant dependenices
    ansible.builtin.command: npm install 
    args:
      chdir: /app
  
  - name: copy cart.service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: load service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enabled service
    ansible.builtin.service:
      name: cart 
      state: started
      enabled: yes
