- name: install redis component
  hosts: redis
  become: yes
  tasks:
  
  - name: Disable default Redis module
    ansible.builtin.command: dnf module disable redis -y

  - name: Ensure Redis module is enabled from AppStream
    ansible.builtin.command: dnf module enable redis -y

  - name: Install Redis
    ansible.builtin.package:
     name: redis
     state: present


  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes