- name: user component
  hosts: user
  become: yes
  tasks:
  - name: enable and disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create user
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download user applications
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user.zip 
      dest: /tmp

  - name: extract user applcations 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: instant dependenices
    ansible.builtin.command: npm install 
    args:
      chdir: /app
  
  - name: copy user.service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: load service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enabled service
    ansible.builtin.service:
      name: user 
      state: started
      enabled: yes

  - name: copy mongodb
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell 
      state: present

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.manacars.shop  < /app/schema/user.js